### ISSUE TITLE
Add hypothesis for control comparison

### ISSUE THREAD

**Issue by lizgehret** [qiime2/q2-fmt#12]
We should add in a hypothesis for _comparewisesons_ (pair-wise comparisons) between controls (if there are multiple control groups).

**Comment by ebolyen** [comment]
Isn't that `all-pairwise` for `mann_whitney_u`?

**Comment by thermokarst** [comment]
> comparewisesons 

Can you define this, that way others who might want to contribute or follow along with this plugin know what it means?

**Comment by lizgehret** [comment]
> Isn't that `all-pairwise` for `mann_whitney_u`?

@ebolyen it's close, but we had discussed a variation on this where we are _only_ comparing the individual control groups  (vs. controls and references). Do you still think this would be a helpful variation on the 'all-pairwise' hypothesis that we already have? And if so, maybe this can just look like a parameter that will exclude a subset of the reference distribution.

**Comment by ebolyen** [comment]
I see, I think we're probably fine with just the `control` hypothesis in that case. If you have multiple interesting comparisons, you can either pick each one individually (and we add a merge stats which recalcs the FDR column), or you do all-pairwise and just look at the ones you cared about.
