### ISSUE TITLE
Add hypotheses from Greg's autism study

### ISSUE THREAD

**Issue by lizgehret** [qiime2/q2-fmt#13]
We should add in the hypotheses used in Greg's autism study, found [here](https://github.com/caporaso-lab/autism-fmt1/blob/18-month-followup/16S/engraftment.ipynb).

**Comment by ebolyen** [comment]
Which ones are we missing? I think we've covered them all, and actually added a few (like consecutive).

**Comment by lizgehret** [comment]
You're right @ebolyen, thanks! Closing this issue.
