### ISSUE TITLE
Check for increase in alpha/beta diversity from baseline

### ISSUE THREAD

**Issue by lizgehret** [qiime2/q2-fmt#14]
**Alpha Diversity**:
We should add a hypothesis (or potentially a parameter in the baseline hypothesis that already exists) to check for an _increase_ in alpha diversity.

This could also be housed (as a parameter to check for increase) under a check for the difference in alpha diversity at a single time point (week vs. control).

**Beta Diversity**:
Is distance to donor significantly lower (not just different) than it was at baseline (week 0, i.e. pre-FMT)?

`wilcoxon_srt` with `baseline_group = 0`, and alternative of **greater/lesser** depending on ordering (should be documented very explicitly - thanks @ebolyen).

**Comment by ebolyen** [comment]
Yeah! We should do this with an `alternative_hypothesis` parameter, which can be two-sided, greater, or lesser.

**Comment by lizgehret** [comment]
Solved by #19
