### ISSUE TITLE
Beta diversity: new hypothesis

### ISSUE THREAD

**Issue by lizgehret** [qiime2/q2-fmt#16]
We should add the following hypothesis for beta diversity:

Beta[donor, subject]_w < Beta[donor, subject]_0

**Comment by ebolyen** [comment]
This would be:

1. `group_timepoints` with beta div and subject
2. `wilcoxon_srt` with `baseline_group = 0`, and alternative of greater/lesser depending on ordering (which we should document very explicitly).

So I think this would be solved by #14 as well. As we can already ask the `!=` version of this question.
